name = "Coexist"
uuid = "08789a54-ca73-42e4-a4a6-0e903b52103e"
authors = ["Sebastian Vollmer", "Aadesh Deshmukh", "Dinesh Vikram", "Gergo Bohner"]
version = "0.1.0"

[deps]
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SciPyDiffEq = "505e40e9-d84e-434c-8501-7161967c02cb"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
